### PR TITLE
Use buffer-scope instead of window-scope variables

### PR DESCRIPTION
**Pull request by adam-szaj**

### CODE REVIEW

**Comment by adam-szaj** [comment]
> What is the reason for this change? Actually I chose the window scope intentionally because I wanted to be able to have different foldsearch views on the same buffer in different windows and be able to modify them independent. Having a buffer scope would change the variables of the same buffer in another window and thus might have side effects if you do a `:Fe` and `:Fl` there.

I get your point, my use case is quite opposite to yours, I usually work in one window with many buffers. So if I want to perform foldsearch on more than one buffer, with usually different search pattern, it is a kind of mess, I cannot even unfold with `<leader>fe`. I think our cases are both valid, but our solutions are not good for both of us.

Maybe tab-scope variables would work for us? I'll try.

_BTW this plugin makes vim a winner for me in most cases._

**Comment by embear** [comment]
I already have a draft plan to add this scope feature. No need for you to dive into vim scripting. I'll try to push a feature branch this evening for testing.

**Comment by embear** [comment]
There is a branch `feature/scope` that contains the new code. When you set `let g:foldsearch_scope = 'window'` then you should get the same behavior as in your PR.

**Comment by embear** [comment]
Assuming that latest changes work as expected ....

**Pull request closed without merging**
